"""tablas_iniciales

Revision ID: 0d478c7ae52f
Revises: 
Create Date: 2026-02-05 15:02:12.211721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d478c7ae52f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administradores',
    sa.Column('id_admin', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_admin'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('guardias',
    sa.Column('id_guardia', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_guardia'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('puntos_control',
    sa.Column('id_punto', sa.Integer(), nullable=False),
    sa.Column('nombre_zona', sa.String(length=100), nullable=True),
    sa.Column('token_qr', sa.String(length=100), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('radio_permitido', sa.Integer(), nullable=True),
    sa.Column('numero_orden', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_punto'),
    sa.UniqueConstraint('token_qr')
    )
    op.create_table('registros_ronda',
    sa.Column('id_registro', sa.BigInteger(), nullable=False),
    sa.Column('id_guardia', sa.Integer(), nullable=True),
    sa.Column('id_punto', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.Column('lat_real', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('long_real', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('distancia_error', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_guardia'], ['guardias.id_guardia'], ),
    sa.ForeignKeyConstraint(['id_punto'], ['puntos_control.id_punto'], ),
    sa.PrimaryKeyConstraint('id_registro')
    )
    op.create_index(op.f('ix_registros_ronda_fecha_hora'), 'registros_ronda', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_registros_ronda_id_guardia'), 'registros_ronda', ['id_guardia'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros_ronda')
    op.drop_table('puntos_control')
    op.drop_table('guardias')
    op.drop_table('administradores')
    # ### end Alembic commands ###
