"""Agregar tabla DestinatarioReporte

Revision ID: 2dee666f7d8c
Revises: 0d478c7ae52f
Create Date: 2026-04-07 13:39:03.988253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dee666f7d8c'
down_revision = '0d478c7ae52f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinatarios_reporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )



def downgrade():

    op.drop_table('destinatarios_reporte')
    # ### end Alembic commands ###
