"""Inicializacion completa con indices y SET NULL

Revision ID: 49120c7140d6
Revises: 
Create Date: 2026-04-14 20:36:06.449009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49120c7140d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administradores',
    sa.Column('id_admin', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_admin'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('destinatarios_reporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sedes',
    sa.Column('id_sede', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_sede'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('guardias',
    sa.Column('id_guardia', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('id_sede', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_sede'], ['sedes.id_sede'], ),
    sa.PrimaryKeyConstraint('id_guardia'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('puntos_control',
    sa.Column('id_punto', sa.Integer(), nullable=False),
    sa.Column('nombre_zona', sa.String(length=100), nullable=True),
    sa.Column('token_qr', sa.String(length=100), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('radio_permitido', sa.Integer(), nullable=True),
    sa.Column('numero_orden', sa.Integer(), nullable=True),
    sa.Column('id_sede', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_sede'], ['sedes.id_sede'], ),
    sa.PrimaryKeyConstraint('id_punto'),
    sa.UniqueConstraint('token_qr')
    )
    op.create_table('registros_ronda',
    sa.Column('id_registro', sa.BigInteger(), nullable=False),
    sa.Column('id_guardia', sa.Integer(), nullable=True),
    sa.Column('id_punto', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.Column('lat_real', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('long_real', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('distancia_error', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_guardia'], ['guardias.id_guardia'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_punto'], ['puntos_control.id_punto'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_registro')
    )
    with op.batch_alter_table('registros_ronda', schema=None) as batch_op:
        batch_op.create_index('ix_ronda_fecha_hora', ['fecha_hora'], unique=False)
        batch_op.create_index('ix_ronda_guardia_fecha', ['id_guardia', 'fecha_hora'], unique=False)
        batch_op.create_index('ix_ronda_id_punto', ['id_punto'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_ronda', schema=None) as batch_op:
        batch_op.drop_index('ix_ronda_id_punto')
        batch_op.drop_index('ix_ronda_guardia_fecha')
        batch_op.drop_index('ix_ronda_fecha_hora')

    op.drop_table('registros_ronda')
    op.drop_table('puntos_control')
    op.drop_table('guardias')
    op.drop_table('sedes')
    op.drop_table('destinatarios_reporte')
    op.drop_table('administradores')
    # ### end Alembic commands ###
