"""Agregar modelo de Sedes

Revision ID: 5e45a088fba7
Revises: 2dee666f7d8c
Create Date: 2026-04-07 22:20:22.670244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e45a088fba7'
down_revision = '2dee666f7d8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sedes',
    sa.Column('id_sede', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_sede'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('guardias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_sede', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sedes', ['id_sede'], ['id_sede'])

    with op.batch_alter_table('puntos_control', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_sede', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sedes', ['id_sede'], ['id_sede'])

    with op.batch_alter_table('registros_ronda', schema=None) as batch_op:
        # ¡Líneas conflictivas comentadas para que MySQL no reclame!
        # batch_op.drop_index(batch_op.f('ix_registros_ronda_fecha_hora'))
        # batch_op.drop_index(batch_op.f('ix_registros_ronda_id_guardia'))
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_ronda', schema=None) as batch_op:
        # ¡Líneas conflictivas comentadas!
        # batch_op.create_index(batch_op.f('ix_registros_ronda_id_guardia'), ['id_guardia'], unique=False)
        # batch_op.create_index(batch_op.f('ix_registros_ronda_fecha_hora'), ['fecha_hora'], unique=False)
        pass

    with op.batch_alter_table('puntos_control', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_sede')

    with op.batch_alter_table('guardias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_sede')

    op.drop_table('sedes')
    # ### end Alembic commands ###